In [133]:
import numpy as np
import itertools 

In [134]:
# simple case; starts with 2 nodes and simple logic 
# all nodes 
logic = np.array([[1,0],
                  [-2,1]])
initial = np.array([[0, 0],[0, 1],[1, 0],[1, 1]])

trajectory = initial.dot(logic)
print(trajectory)

[[ 0  0]
 [-2  1]
 [ 1  0]
 [-1  1]]


In [135]:
random_logic = np.random.randint(-3, 3,(3,3))
print(random_logic)

[[-3  1 -2]
 [-2  2  2]
 [-2 -2 -1]]


In [136]:
# number = 10 by 2^10 array 
#initial_state = np.array((2^10, 10))

k =4
#ini_state = [np.array(i,2**i) for i in itertools.product([0,1], repeat = k)] # able to change repeat value 
ini_state = [list(i) for i in itertools.product([0,1], repeat = k)] 

n = 2**(k)

#logic_n10 = np.array([[1,0],[-2,1],[2,3],[-2,-4],[1,0],[5,0],[-3,1],[1,-1],[2,2],[3,-2]])
logic_n3 = np.array([[1,0,1,2],[-2,-5,3,1],[-3,1,0,2],[1,3,-2,-1]])
#random_logic = np.random.randint(-3, 3,(n,n)) # matrix
#random_logic = np.random.randint(-3,3, size = (n,n))
#print(n)
#print(random_logic)

trajectory =[]
attractors =[]
attractors_dup =[]
#for i in range(0,7): # 2^n -1 

for i in range(0,k):
    current = ini_state[0]
    trajectory.append(ini_state[i])
    #next_state = random_logic.dot(ini_state[i])
    next_state = logic_n3.dot(ini_state[i])
    
    def weight_sum(next_state):
        for idx in range(next_state.shape[0]):
            if next_state[idx] >= 0:
                next_state[idx] =1
            else:
                next_state[idx] =0
        return next_state
    
########### check whether there is same array in trajectory ######
        if weight_sum(next_state) in trajectory:
            attractor.append(weight_sum(next_state)) # 나중에 한꺼번에 count할 것이기 때문에 반복해서 만들어져도 괜찮음? 
        else: # if there is no same array in trajectory
            trajectory.append(weight_sum(next_state))
#print(next_state)
#print(trajectory)
#print(type(next_state))
#print(attractors)   

for item in attractors:
    if attractors.count(item) > 1:
        attractors_dup.append(item)

attractors_dup_set = set(attractors_dup)

print(attractors_dup_set)   
    
# if specific array in trajectory -> assign it as attractor
# trajcetory에 이미 존재한다면 끌개로 분류한 다음에 끌개 저장 공강 및 끌개유역크기 저장배열을 만들고, 끌개 유역 크기 저장배열에 1을 입력
# 다음 끌개 만들때 이미 존재하는 끌개라면 끌개 크기 하나 더 만들고 다음 끌개 저장공간에 저장 
# 만약 없다면 저장하고 초기조건 다음 array에 대해서 한다. 



set()


In [137]:
trajectory = [1,1,2,3,3]

def dup(trajectory):
    attractors = dict()
    for elem in trajectory:
        if elem in attractors:
            attractors[elem] +=1
        else:
            attractors[elem] = 1
    attractors = { key:value for key, value in attractors.items() if value >1}
    return attractors


attractors = dup(trajectory)

for key, value in attractors.items():
    print(key, '::', value)
    

1 :: 2
3 :: 2


In [138]:
sample_trajectory = [1,1,2,3,3]
sample_attractors = []

for item in sample_trajectory:
    if sample_trajectory.count(item) > 1:
        sample_attractors.append(item)
sample_attractors_set = set(sample_attractors)
#print(sample_attractors_set)
print(len(sample_attractors_set))
print(sample_attractors_set[0])
for i in len(sample_attractors_set):
    sample_attractos.count(sample_attractors())
#sample_attractors.count(sample_attractos(i))

{1, 3}
2


TypeError: 'set' object is not subscriptable